import sys
import unittest
import requests
import json

class TestController(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_controllerrunning(self):
        try:
            r = requests.get('http://localhost:5000/')
            self.assertEqual(r.status_code, 200)
            self.assertNotEqual(r.json().get('about', 'UNEXPECTED RESPONSE'), 'UNEXPECTED RESPONSE')
        except Exception:
            self.assertEqual('', 'Controller not running!')

    def test_newgame(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        error = r.json().get('error', '')
        self.assertEqual(error, '')
        gameID = r.json().get('game_id', '')
        self.assertNotEqual(gameID, '')

    def test_addplayer(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        self.assertEqual(r.status_code, 200)
        game_id = r.json().get('game_id', '')
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Alice'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertIn('players', status)
        self.assertIn('Alice', [p['name'] for p in status['players']])

    def test_newhand(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        self.assertEqual(r.status_code, 200)
        game_id = r.json().get('game_id', '')
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Alice'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Bob'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Janet'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'John'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        playernames = [p['name'] for p in status['players']]
        self.assertIn('Alice', playernames)
        self.assertIn('Bob', playernames)
        self.assertIn('Janet', playernames)
        self.assertIn('John', playernames)
        r = requests.post('http://localhost:5000/newhand', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual(100, status['small_blind'])
        self.assertEqual(200, status['big_blind'])
        self.assertEqual('Janet', status['current_hand']['first_player'])

    def test_badactor(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        self.assertEqual(r.status_code, 200)
        game_id = r.json().get('game_id', '')
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Alice'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Bob'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Janet'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'John'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        playernames = [p['name'] for p in status['players']]
        self.assertIn('Alice', playernames)
        self.assertIn('Bob', playernames)
        self.assertIn('Janet', playernames)
        self.assertIn('John', playernames)
        r = requests.post('http://localhost:5000/newhand', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('Janet', status['current_hand']['first_player'])
        # incomplete parameters on act
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet'})
        self.assertEqual(r.status_code, 400)
        status = r.json()
        self.assertEqual("Missing parameters('player', 'action')", status['error'])
        # wrong actor
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'call'})
        self.assertEqual(r.status_code, 400)
        status = r.json()
        self.assertEqual("Player not allowed", status['error'])
        # wrong option
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'check'})
        self.assertEqual(r.status_code, 400)
        status = r.json()
        self.assertEqual("Action not allowed", status['error'])
        # bet without value
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'bet'})
        self.assertEqual(r.status_code, 400)
        status = r.json()
        self.assertEqual("Bet minimum is big blind", status['error'])

    def test_flop(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        self.assertEqual(r.status_code, 200)
        game_id = r.json().get('game_id', '')
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Alice'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Bob'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Janet'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'John'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        playernames = [p['name'] for p in status['players']]
        self.assertIn('Alice', playernames)
        self.assertIn('Bob', playernames)
        self.assertIn('Janet', playernames)
        self.assertIn('John', playernames)
        r = requests.post('http://localhost:5000/newhand', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual(100, status['small_blind'])
        self.assertEqual(200, status['big_blind'])
        self.assertEqual('Janet', status['current_hand']['first_player'])
        self.assertEqual('Janet', status['current_hand']['current_player']['name'])
        self.assertEqual(['bet', 'fold'], status['current_hand']['current_player']['options'])
        self.assertEqual('', status['current_hand']['last_player'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/flop', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('flop', status['current_hand']['round'])

    def test_turn(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        self.assertEqual(r.status_code, 200)
        game_id = r.json().get('game_id', '')
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Alice'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Bob'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Janet'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'John'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        playernames = [p['name'] for p in status['players']]
        self.assertIn('Alice', playernames)
        self.assertIn('Bob', playernames)
        self.assertIn('Janet', playernames)
        self.assertIn('John', playernames)
        r = requests.post('http://localhost:5000/newhand', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual(100, status['small_blind'])
        self.assertEqual(200, status['big_blind'])
        self.assertEqual('Janet', status['current_hand']['first_player'])
        self.assertEqual('Janet', status['current_hand']['current_player']['name'])
        self.assertEqual(['bet', 'fold'], status['current_hand']['current_player']['options'])
        self.assertEqual('', status['current_hand']['last_player'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/flop', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/turn', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('turn', status['current_hand']['round'])

    def test_river(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        self.assertEqual(r.status_code, 200)
        game_id = r.json().get('game_id', '')
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Alice'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Bob'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Janet'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'John'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        playernames = [p['name'] for p in status['players']]
        self.assertIn('Alice', playernames)
        self.assertIn('Bob', playernames)
        self.assertIn('Janet', playernames)
        self.assertIn('John', playernames)
        r = requests.post('http://localhost:5000/newhand', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual(100, status['small_blind'])
        self.assertEqual(200, status['big_blind'])
        self.assertEqual('Janet', status['current_hand']['first_player'])
        self.assertEqual('Janet', status['current_hand']['current_player']['name'])
        self.assertEqual(['bet', 'fold'], status['current_hand']['current_player']['options'])
        self.assertEqual('', status['current_hand']['last_player'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/flop', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/turn', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('turn', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/river', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('river', status['current_hand']['round'])

    def test_showdown(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        self.assertEqual(r.status_code, 200)
        game_id = r.json().get('game_id', '')
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Alice'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Bob'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Janet'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'John'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        playernames = [p['name'] for p in status['players']]
        self.assertIn('Alice', playernames)
        self.assertIn('Bob', playernames)
        self.assertIn('Janet', playernames)
        self.assertIn('John', playernames)
        r = requests.post('http://localhost:5000/newhand', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual(100, status['small_blind'])
        self.assertEqual(200, status['big_blind'])
        self.assertEqual('Janet', status['current_hand']['first_player'])
        self.assertEqual('Janet', status['current_hand']['current_player']['name'])
        self.assertEqual(['bet', 'fold'], status['current_hand']['current_player']['options'])
        self.assertEqual('', status['current_hand']['last_player'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/flop', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/turn', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('turn', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/river', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('river', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        self.assertEqual(r.status_code, 200)
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'check'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('Y', status['current_hand']['done'])
        self.assertEqual('showdown' in status['current_hand'], False)
        r = requests.post('http://localhost:5000/showdown', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('current_hand' in status, True)
        self.assertEqual(status['current_hand']['done'], 'Y')
        self.assertEqual('payout' in status['current_hand'], True)
        self.assertEqual('showdown' in status['current_hand'], True)        
        self.assertEqual('winninghands' in status['current_hand'], True)        

    def test_fold(self):
        r = requests.post('http://localhost:5000/endgame')
        self.assertEqual(r.status_code, 204)
        r = requests.post('http://localhost:5000/startgame')
        self.assertEqual(r.status_code, 200)
        game_id = r.json().get('game_id', '')
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Alice'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Bob'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'Janet'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.post('http://localhost:5000/addplayer', json={'game_id': game_id, 'name': 'John'})
        self.assertEqual(r.status_code, 200)
        res = r.json()
        self.assertNotEqual('', res['player_id'])
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        playernames = [p['name'] for p in status['players']]
        self.assertIn('Alice', playernames)
        self.assertIn('Bob', playernames)
        self.assertIn('Janet', playernames)
        self.assertIn('John', playernames)
        r = requests.post('http://localhost:5000/newhand', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual(100, status['small_blind'])
        self.assertEqual(200, status['big_blind'])
        self.assertEqual('Janet', status['current_hand']['first_player'])
        self.assertEqual('Janet', status['current_hand']['current_player']['name'])
        self.assertEqual(['bet', 'fold'], status['current_hand']['current_player']['options'])
        self.assertEqual('', status['current_hand']['last_player'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'call'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'John', 'action': 'all-in'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Alice', 'action': 'fold'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Bob', 'action': 'fold'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        r = requests.post('http://localhost:5000/act', json={'game_id': game_id, 'player': 'Janet', 'action': 'fold'})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual('pre-flop', status['current_hand']['round'])
        self.assertEqual('Y', status['current_hand']['done'])
        r = requests.post('http://localhost:5000/flop', json={'game_id': game_id})
        self.assertEqual(r.status_code, 200)
        status = r.json()
        self.assertEqual(status['handfinished'], 'Y')
        r = requests.post('http://localhost:5000/showdown', json={'game_id': game_id})
        self.assertEqual(r.status_code, 204)
        r = requests.get('http://localhost:5000/game/'+game_id)
        status = r.json()
        self.assertEqual(True, 'current_hand' in status)
        self.assertEqual('Y', status['current_hand']['done'])
        self.assertEqual(len(status['current_hand']['winninghands']), 1)
        self.assertEqual('John' in status['current_hand']['winninghands'][0], True)
        self.assertEqual('John' in status['current_hand']['payout'][0], True)
        self.assertEqual(status['current_hand']['payout'][0]['John'], 5500)
        self.assertEqual(False, 'showdown' in status['current_hand'])

if __name__ == '__main__':
    try:
        r = requests.get('http://localhost:5000/')
        if r.status_code != 200:
            raise Exception()
    except:
        print('ERROR: API server may not be running')
        sys.exit(0)

    unittest.main()
